language: node_js
before_install:
  - npm install -g jspm
  - npm install -g npm@'>=3.5.0'
  - jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
node_js:
  - "5.1"
  - "5.0"
  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
